### ISSUE TITLE
Is there a way to turn off bounces on scroll in case with iOS?

### ISSUE THREAD

**Issue by kulbachenko** [rodydavis/easy_web_view#11]
Hello! 
Thanks for this very useful web view!
Is there a way to turn off bounces on scroll in case with iOS?

**Comment by omartinma** [comment]
Hi! Any update or workaround on this issue @rodydavis ?

**Comment by rodydavis** [comment]
This is using the flutter_webview under the hood. If that can do it then I can pass the option

**Comment by rodydavis** [comment]
I am open to PRs

**Comment by rodydavis** [comment]
This package is only for easy implementation of a webview to show content from a url. If you want to have full control please fork the plugin and use the components directly.
