### ISSUE TITLE
Javascript player works in Chrome, but not mobile

### ISSUE THREAD

**Issue by jameswasher** [rodydavis/easy_web_view#12]
I'm sure I'm doing something wrong, but I can't get EasyWebView to work in mobile (iOS or android) for a javascript video player.  It will load a webpage (e.g. flutter.dev) fine but not the video player.  Any ideas?  Thanks!

`import 'dart:async';

import 'package:easy_web_view/easy_web_view.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Material App Bar'),
        ),
        body: Column(
          children: <Widget>[
            Flexible(
              child: EasyWebView(
                src:
                    'http://dev.theinfiniteactuary.com/player3.php?lesson=35102',
                // 'http://flutter.dev',
                isHtml: false, // Use Html syntax
                isMarkdown: false, // Use markdown syntax
                convertToWidets: false, // Try to convert to flutter widget
              ),
            ),
            // Flexible(child: Container()),
          ],
        ),
      ),
    );
  }
}`

**Comment by rodydavis** [comment]
Make sure the content can load on an iframe! But I’ll look into this 👍🏼

**Comment by rodydavis** [comment]
Please use the video_player package for videos
