### ISSUE TITLE
Listen for events

### ISSUE THREAD

**Issue by timosturm** [rodydavis/easy_web_view#17]
Is it planned to support event listeners for the content of the web view?
I am searching for a way to embed a website in a flutter (web) project and I need to access the currently displayed url of the widget.

E.g. wikipedia is embedded, the user clicks on a link, an event is fired that contains the new url.

**Comment by rodydavis** [comment]
Only for when it is loaded. I’m open for PRs!

**Comment by aliakkawi** [comment]
Hi,
In Issue #5 you already mentioned that you have already implemented that, is there a listener for url change?

**Comment by rodydavis** [comment]
Not for url change. I only have a callback for when the frame loads on the web or the controller changes on mobile. I’m open to PRs though. Anything in this package has to support all platforms

**Comment by vlowe85** [comment]
I found the lack of event on url change quit annoying too. Fortunately for me i also controlled the website i was putting in the iframe so i could do a workaround with `postMessage`.

**Comment by rodydavis** [comment]
Im open to PR’s but this also has to support ios/android and eventually desktop. I could not find a way to listen to url changes there.

**Comment by timosturm** [comment]
The official web-view plugin for flutter has the same problem ([see](https://github.com/flutter/flutter/issues/45295)), when using javascripts  `iframe` this is generally not possible.

The [community plugin](https://github.com/fluttercommunity/flutter_webview_plugin) for web-views allegedly supports web, and seems to provide such callbacks. But I could not get that to run on web.

Maybe someone else has more luck or knowledge than me and can use this information.

**Comment by minhnhatvdl** [comment]
> I found the lack of event on url change quite annoying too. Fortunately for me i also controlled the website i was putting in the iframe so i could do a workaround with `postMessage`.

Could you show me how to implement postMessage with your iframe in flutter web ? I try it but can't listen a message sent by postMessage from iframe.

**Comment by vlowe85** [comment]
> > I found the lack of event on url change quite annoying too. Fortunately for me i also controlled the website i was putting in the iframe so i could do a workaround with `postMessage`.
> 
> Could you show me how to implement postMessage with your iframe in flutter web ? I try it but can't listen a message sent by postMessage from iframe.

Try like this..
  
```
window.addEventListener("message", (event) async {
    MessageEvent messageEvent = event;
    print("flutter got ${messageEvent.data.toString()}");
}, false);
```


you will need `import 'dart:html';`

**Comment by minhnhatvdl** [comment]
> > > I found the lack of event on url change quite annoying too. Fortunately for me i also controlled the website i was putting in the iframe so i could do a workaround with `postMessage`.
> > 
> > 
> > Could you show me how to implement postMessage with your iframe in flutter web ? I try it but can't listen a message sent by postMessage from iframe.
> 
> Try like this..
> 
> ```
> window.addEventListener("message", (event) async {
>     MessageEvent messageEvent = event;
>     print("flutter got ${messageEvent.data.toString()}");
> }, false);
> ```
> 
> you will need `import 'dart:html';`

Which channel and version of flutter are you on ? I am using flutter version 1.12.13+hotfix.6 channel beta. Your code seems not working for me. Thank you.

**Comment by minhnhatvdl** [comment]
It works for me now. Thank you all :)

**Comment by rodydavis** [comment]
This package is only for easy implementation of a webview to show content from a url. If you want to have full control please fork the plugin and use the components directly.

**Comment by giiyms** [comment]
> > > I found the lack of event on url change quite annoying too. Fortunately for me i also controlled the website i was putting in the iframe so i could do a workaround with `postMessage`.
> > 
> > 
> > Could you show me how to implement postMessage with your iframe in flutter web ? I try it but can't listen a message sent by postMessage from iframe.
> 
> Try like this..
> 
> ```
> window.addEventListener("message", (event) async {
>     MessageEvent messageEvent = event;
>     print("flutter got ${messageEvent.data.toString()}");
> }, false);
> ```
> 
> you will need `import 'dart:html';`

Where are you meant to put this code?
