### ISSUE TITLE
Wrap height based on HTML content

### ISSUE THREAD

**Issue by namchuai** [rodydavis/easy_web_view#19]
Hello,
Thank you for the great library. I was looking for some library to display html on web (so ironic) xD. Then I came across this library.

I have a question about make the EasyWebView's height became wrap_content when rendering my HTML. Is this possible?

Thank you and have a nice day!

**Comment by rodydavis** [comment]
Thanks for the suggestion! It is outside of the scope of this plugin as I want this to focus on the minimal setup needed to show a webview in an app with just a url. I’m always open to PRs though!
