### ISSUE TITLE
Background color issue

### ISSUE THREAD

**Issue by diegothucao** [rodydavis/easy_web_view#2]
Hi mate, 
I am using easy web view lib. I face an issue is 
I set the theme background as dark gray but when i open the Webview, it first show white color and until the web is loaded then it changes to default background color?
Could you support how to fix it ?

**Comment by rodydavis** [comment]
Issue on what platform?

**Comment by diegothucao** [comment]
Both IOS and Android, let me send you an video.

**Comment by rodydavis** [comment]
Hmm 🤔 this is just the web view under the hood. Are background properties exposed with flutter_webview?

**Comment by rodydavis** [comment]
Im still looking into see how to fix this. Have you come up with a solution on your own? I am open to PRs

**Comment by RaghuMudem** [comment]
Hi @diegothucao ,

Can you help me to set theme background for my webview. If you guide me with a flutter code clue, that would be a great help.

**Comment by rodydavis** [comment]
Fixed on **2.0.1**!
