### ISSUE TITLE
Any callback if URL cannot be reached because of (say) no internet ?

### ISSUE THREAD

**Issue by ssbaval** [rodydavis/easy_web_view#22]
Can we have an errorBuilder widget supplied to EasyWebView. This would be invoked if there was an exception launching the URL or URL could not be loaded etc ...

at the moment there is an onLoaded callback but this gets fired regardless of whether the URL could be accessed ....

**Comment by rodydavis** [comment]
I would suggest checking for internet not using this plugin. The connectivity plugin is great for that
