### ISSUE TITLE
Screen Flash when using appbar (web)

### ISSUE THREAD

**Issue by bkr32** [rodydavis/easy_web_view#25]
when viewing a page under appbar and hovering over a button ie back the screen flashes when the label appears

**Comment by rodydavis** [comment]
You need to wrap with webview with a RepaintBoundary then

**Comment by bkr32** [comment]
```RepaintBoundary(
            child: EasyWebView(
                src: html,
                isHtml: true,
                onLoaded: () {
                },
              ),
          )```
like this? unfortunately the issue persists

**Comment by rodydavis** [comment]
Also an issue with HTML elements in flutter right now

**Comment by pinpong** [comment]
related to https://github.com/flutter/flutter/issues/56257
