### ISSUE TITLE
Track Src

### ISSUE THREAD

**Issue by Heinrich-vanNieuwenhuizen** [rodydavis/easy_web_view#28]
Hi, I tried everything, to get the IframeElement source to be tracked.

The issue is that I  have a callback URL, meaning when the IFrame eventually reaches the URL, the IFrame should pop.

**Comment by rodydavis** [comment]
The api would need to work for the webview on iOS and android and because of that it is outside the scope of the plugin. Please feel free to fork it and add a PR
