### ISSUE TITLE
Please update cupertino_icons dependency

### ISSUE THREAD

**Issue by slavap** [rodydavis/easy_web_view#31]
Error: easy_web_view 1.3.0 depends on cupertino_icons ^0.1.2 and no versions of easy_web_view match >1.3.0 <2.0.0
when using cupertino_icons: ^1.0.0

**Comment by rodydavis** [comment]
Feel free to make a pull request! I don't believe this package should have to rely on Cupertino icons anyway. Might as well remove it￼

**Comment by shatanikmahanty** [comment]
@rodydavis please accept the pull request from @slavap as I think this solves the issue

**Comment by rodydavis** [comment]
Ok Ill look into it rn
