### ISSUE TITLE
Proper Html is not rendered

### ISSUE THREAD

**Issue by rt16** [rodydavis/easy_web_view#35]
I am using this widget for loading the Html content.
EasyWebView(
                convertToWidgets: true,
                 src:"<html>
                     <head>
                     <meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
                      <style type="text/css" style="display:none;"> P {margin-top:0;margin-bottom:0;} </style>
                     </head>
                           <body dir="ltr">
                      <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                           Thank you doctor&nbsp;</div>
                          <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                      we will follow as advised</div>
                       <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                  <br>
                   </div> ",
                isHtml: true,
                isMarkdown: false, onLoaded: () { 
                 },
              ),

This is my html String
<html>
                     <head>
                     <meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
                      <style type="text/css" style="display:none;"> P {margin-top:0;margin-bottom:0;} </style>
                     </head>
                           <body dir="ltr">
                      <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                           Thank you doctor&nbsp;</div>
                          <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                      we will follow as advised</div>
                       <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                  <br>
                   </div>

The output is :
![668ad5b3-063f-4636-92ca-b0fe0e555f62](https://user-images.githubusercontent.com/48627488/94691813-682cd380-034f-11eb-9d53-0bafbd4cf6cf.jpg)

The Output that i'm getting is showing the text 
P {margin-top:0;margin-bottom:0;} Along with the output content.
Any Possibility to show the proper output

**Comment by rt16** [comment]
<html>
                     <head>
                     <meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
                      <style type="text/css" style="display:none;"> P {margin-top:0;margin-bottom:0;} </style>
                     </head>
                           <body dir="ltr">
                      <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                           Thank you doctor&nbsp;</div>
                          <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                      we will follow as advised</div>
                       <div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);">
                  <br>
                   </div>

**Comment by rodydavis** [comment]
That's not the purpose of convert to widgets, it only reads inline styles
