### ISSUE TITLE
WebView rebuilding/reloading inside of CustomScrollView

### ISSUE THREAD

**Issue by carman247** [rodydavis/easy_web_view#4]
Hi, this WebView is great, it's the only one I've managed to get to work with Flutter-Web.

I'm having problems when using it inside of a CustomScrollView>SliverList and wondering if you could advise what to do? When I scroll the WebView widget will reload/rebuild, this doesn't happen when it's used inside of a SingleChildScrollView, so I guess it has something to do with widgets being destroyed...  I've tried to stop this happening by using "automatickeepaliveclientmixin" on a Stateful widget but I didn't work. I'm pretty sure I was doing it correctly.

**Comment by rodydavis** [comment]
Yeah not sure I have some similar issues, but if I find a solution I will update!

**Comment by MypaceEngine** [comment]
Thank you for your awesome plugin.

I had same problem.
I tried some case of screen arrangement, and I got workaround about no reloading iframe.
In my case, floatingActionButton is added to application, reading is stopped.
      floatingActionButton: FloatingActionButton(
        backgroundColor: Colors.black.withAlpha(0),
        elevation: 0.0,
      ),

Thanks

**Comment by rodydavis** [comment]
Wow weird!

**Comment by rodydavis** [comment]
This will get fixed when a flutter issues is resolved. It is common to the HTMLPlatformView

**Comment by rodydavis** [comment]
Fixed on 1.1.2
