### ISSUE TITLE
Part of the window dialog(showDatePicker) that falls on top of the pdf(EasyWebView) does not work, not react

### ISSUE THREAD

**Issue by SergeiEensalu** [rodydavis/easy_web_view#42]
Hi!

I described the problem on the [forum](https://stackoverflow.com/questions/65633312/part-of-the-window-dialogshowdatepicker-that-falls-on-top-of-the-pdfeasywebvi). I want to add that none of the widgets that are on top of EasyWebView work

**Comment by AmethystLiang** [comment]
Having the same issue.

**Comment by nwparker** [comment]
This seems like the relevant Flutter issues (with a potential solution posted there)
https://github.com/flutter/flutter/issues/54027
