### ISSUE TITLE
Flutter web finding a way to monitor the requested Url "navigationDelegate"

### ISSUE THREAD

**Issue by abdulmalekDery** [rodydavis/easy_web_view#45]
In the native webview there is a property called 

        WebView(
                      initialUrl: widget.url,
                      javascriptMode: JavascriptMode.unrestricted,
                      navigationDelegate: (NavigationRequest request) async
                      {
                        if (request.url.startsWith('https://xxxxxx.xxx.xxx/'))
                        {
                          print('blocking navigation to ${request.url}');
                          _navigationService.navigateTo(UYUi.routeName,arguments: request.url);
                          return NavigationDecision.prevent;
                        }

                print('allowing navigation to $request');
                return NavigationDecision.navigate;
              },
            ) 

is there any way to monitor the requests like that in flutter web

**Comment by rodydavis** [comment]
Fixed on version `1.5.0`, reopen if it is still an issue

**Comment by ahetawal-p** [comment]
@rodydavis this still seems to be an issue on Flutter web: https://github.com/rodydavis/easy_web_view/issues/77
