### ISSUE TITLE
Clear Cache Webview/Iframe

### ISSUE THREAD

**Issue by fauzyahmad** [rodydavis/easy_web_view#46]
Hello, this is a wonderfull package for embedding web to flutter app and web version. But I have a question, is there any way to clear cache specific for that iframe just like this package [https://pub.dev/packages/flutter_webview_plugin](url)? I can't find it in the documentation. Thanks

**Comment by rodydavis** [comment]
Not sure if there is a shared interface that can be exposed, but happy to review a PR!
