### ISSUE TITLE
Unable to navigate in the dialog when easy_web_view renders a page

### ISSUE THREAD

**Issue by raveeshajoshi** [rodydavis/easy_web_view#47]
Hi ,

 I have a flutter landing page from where i open few dialogs using showDialog (dialog.dart). In the landing page i am trying to load a section from external html using easy_web_view. Rendering looks fine and works like a charm. But If I open a dialog now i am unable to perform any actions inside the dialog. seems to be easy_web_view in on the top of the stack. Is there any way to come across this.

Regards,
Raveesha Joshi

**Comment by funyin** [comment]
If you have any widgets that are placed above the webView and receive gesture events wrap them with [pointer interceptor](https://pub.dev/packages/pointer_interceptor).
