### ISSUE TITLE
Are there callbacks for loading?

### ISSUE THREAD

**Issue by XinwenCheng** [rodydavis/easy_web_view#5]
Hi, thanks for creating and sharing this useful stuff! I just wanna know if there are callbacks for loading status and failure? It's very useful for my app as it may loading some websites like facebook or twitter from countries where cannot access. Thanks in advance!

**Comment by rodydavis** [comment]
Oh interesting, I will see if there is an api I can expose!

**Comment by sagasti** [comment]
These two would be really helpful:
 
         onPageStarted: (String url) {
            print('Page started loading: $url');
          },
          onPageFinished: (String url) {
            print('Page finished loading: $url');
          },

**Comment by dineshpote26** [comment]
Hi , how to get callback of IFrame loading?

**Comment by rodydavis** [comment]
Still looking to implement this. Need to find a way that works on all browsers

**Comment by rodydavis** [comment]
Added on 1.3.0
