### ISSUE TITLE
Runtime warnings

### ISSUE THREAD

**Issue by xinoxapps** [rodydavis/easy_web_view#50]
../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart:83:9: Warning: Operand of null-aware operation '?.' has type 'EasyWebView' which excludes null.
 - 'EasyWebView' is from 'package:easy_web_view/src/mobile.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart').
    if (widget?.onLoaded != null) {
        ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart:92:14: Warning: Operand of null-aware operation '?.' has type 'EasyWebView' which excludes null.
 - 'EasyWebView' is from 'package:easy_web_view/src/mobile.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart').
      width: widget?.width,
             ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart:93:15: Warning: Operand of null-aware operation '?.' has type 'EasyWebView' which excludes null.
 - 'EasyWebView' is from 'package:easy_web_view/src/mobile.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart').
      height: widget?.height,
              ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart:118:16: Warning: Operand of null-aware operation '?.' has type 'EasyWebView' which excludes null.
 - 'EasyWebView' is from 'package:easy_web_view/src/mobile.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart').
          key: widget?.key,
               ^
../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart:123:17: Warning: Operand of null-aware operation '?.' has type 'EasyWebView' which excludes null.
 - 'EasyWebView' is from 'package:easy_web_view/src/mobile.dart' ('../../flutter/.pub-cache/hosted/pub.dartlang.org/easy_web_view-1.4.0-nullsafety/lib/src/mobile.dart').
            if (widget?.onLoaded != null) {

**Comment by rodydavis** [comment]
Fixed on version `1.5.0`, reopen if it is still an issue
