### ISSUE TITLE
Not Compatible with Crashlytics 

### ISSUE THREAD

**Issue by bbrosius** [rodydavis/easy_web_view#55]
easy_web_view is using an old version of permission_handler and permission_handler_platform_interface that is causing conflicts with Crashyltics. 

`Because permission_handler >=5.0.1+2 <5.1.0 depends on permission_handler_platform_interface 2.0.1 and permission_handler >=5.0.1 <=5.0.1+1 depends on permission_handler_platform_interface ^2.0.1, permission_handler >=5.0.1 <5.1.0 requires permission_handler_platform_interface ^2.0.1.

And because permission_handler ^5.1.0 depends on permission_handler_platform_interface ^2.0.2, permission_handler ^5.0.1 requires permission_handler_platform_interface ^2.0.1.

And because easy_web_view >=1.5.0 depends on permission_handler ^5.0.1+1 and permission_handler_platform_interface ^2.0.1 depends on plugin_platform_interface ^1.0.2, easy_web_view >=1.5.0 requires plugin_platform_interface ^1.0.2.

And because firebase_crashlytics_platform_interface 3.0.3 depends on plugin_platform_interface ^2.0.0 and no versions of firebase_crashlytics_platform_interface match >3.0.3 <4.0.0, easy_web_view >=1.5.0 is incompatible with firebase_crashlytics_platform_interface ^3.0.3.

And because firebase_crashlytics 2.0.3 depends on firebase_crashlytics_platform_interface ^3.0.3 and no versions of firebase_crashlytics match >2.0.3 <3.0.0, easy_web_view >=1.5.0 is incompatible with firebase_crashlytics ^2.0.3.

So, because ov_mobile depends on both firebase_crashlytics ^2.0.3 and easy_web_view ^1.5.0, version solving failed.
pub get failed (1; So, because ov_mobile depends on both firebase_crashlytics ^2.0.3 and easy_web_view ^1.5.0, version solving failed.)
exit code 1`

**Comment by rodydavis** [comment]
Should be fixed now
