### ISSUE TITLE
Not able to scroll (Flutter Web, not sure if the same for Mobile)

### ISSUE THREAD

**Issue by carman247** [rodydavis/easy_web_view#6]
Hi,

I'm not really sure if this is considered an issue, or a bug, but I was wondering if there was a reason, or a workaround for this.

When I have a EasyWebView displayed on a portion of the screen I am no longer able to click+drag on the WebView to scroll the screen, nor can I use the Touchpad to scroll if my mouse is hovering over the WebView.

I'm assuming this is because it is trying to scroll _within_ the WebView, even though the WebView doesn't actually scroll.

Obviously the mouse, or my finger needs to interact with the WebView, but I can't figure out a way to enable both actions (interact with the WebView, and be able to scroll the page).

The only thing I can think of is having some sort of Widget over the top of the WebView, that disappears when clicked, but this probably isn't the most intuitive solution for users, and I also wouldn't know how to do this...

Any help or advice would be greatly appreciated

**Comment by rodydavis** [comment]
I’ll do some thinking and research!

**Comment by rodydavis** [comment]
Fixed on 1.1.2

**Comment by carman247** [comment]
> I’ll do some thinking and research!

awesome, thanks!!

**Comment by rodydavis** [comment]
If I understand correctly you can scroll the web view but not the widget?

You need to wrap a widget with AbsorbPointer if you want the scroll to work.

This would be the same bug as having to inner scroll views competing for the gesture

**Comment by rodydavis** [comment]
Working on this branch but still no success:

https://github.com/rodydavis/easy_web_view/tree/scrolling-and-guestures

Blocked by:

https://github.com/flutter/flutter/issues/35394

**Comment by thedylanwells** [comment]
@rodydavis I can second this issue on Flutter for Web on mobile. It works fine on my computer, but I cannot scroll a PDF on Flutter Web (mobile) for some reason.

**Comment by rodydavis** [comment]
This is an issue with Flutter web this. Feel free to file an issue to the sdk
