### ISSUE TITLE
Bug: does not work with web-browsers (Chrome & Edge)

### ISSUE THREAD

**Issue by berat-cakir** [rodydavis/easy_web_view#60]
It runs fine on mobile (switches to `mobile.dart` in library). However, when executed on Chrome or Edge (`web.dart` is being called) nothing works anymore.

<details>
  <summary>Error message</summary>

> An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:51313/VRDXgP5Yj14=
> Error: Unexpected null value.
>     at Object.throw_ [as throw] (http://localhost:51276/dart_sdk.js:5366:11)
>     at Object.nullCheck (http://localhost:51276/dart_sdk.js:5699:30)
>     at http://localhost:51276/packages/easy_web_view/src/impl.dart.lib.js:1179:19
>     at Object._checkAndCall (http://localhost:51276/dart_sdk.js:5576:16)
>     at Object.dcall (http://localhost:51276/dart_sdk.js:5581:17)
>     at http://localhost:51276/dart_sdk.js:171926:47
>     at IdentityMap.new.putIfAbsent (http://localhost:51276/dart_sdk.js:26765:21)
>     at _engine.PlatformViewManager.new.renderContent (http://localhost:51276/dart_sdk.js:171904:44)
>     at _engine.PlatformViewMessageHandler.new.[_createPlatformView] (http://localhost:51276/dart_sdk.js:171997:43)
>     at _engine.PlatformViewMessageHandler.new.handlePlatformViewCall (http://localhost:51276/dart_sdk.js:172016:36)
>     at _engine.EnginePlatformDispatcher.__.[_sendPlatformMessage] (http://localhost:51276/dart_sdk.js:171477:61)
>     at _engine.EnginePlatformDispatcher.__.sendPlatformMessage (http://localhost:51276/dart_sdk.js:171311:33)
>     at _DefaultBinaryMessenger.[_sendPlatformMessage] (http://localhost:51276/packages/flutter/src/services/system_channels.dart.lib.js:2179:38)
>     at _DefaultBinaryMessenger.send (http://localhost:51276/packages/flutter/src/services/system_channels.dart.lib.js:2223:40)
>     at MethodChannel._invokeMethod (http://localhost:51276/packages/flutter/src/services/system_channels.dart.lib.js:956:50)
>     at _invokeMethod.next (<anonymous>)
>     at runBody (http://localhost:51276/dart_sdk.js:39292:34)
>     at Object._async [as async] (http://localhost:51276/dart_sdk.js:39323:7)
>     at MethodChannel.[_invokeMethod] (http://localhost:51276/packages/flutter/src/services/system_channels.dart.lib.js:954:20)
>     at MethodChannel.invokeMethod (http://localhost:51276/packages/flutter/src/services/system_channels.dart.lib.js:968:33)
>     at platform_view$._HtmlElementViewController.new._initialize (http://localhost:51276/packages/flutter/src/widgets/platform_view.dart.lib.js:655:61)
>     at _initialize.next (<anonymous>)
>     at runBody (http://localhost:51276/dart_sdk.js:39292:34)
>     at Object._async [as async] (http://localhost:51276/dart_sdk.js:39323:7)
>     at platform_view$._HtmlElementViewController.new.[_initialize] (http://localhost:51276/packages/flutter/src/widgets/platform_view.dart.lib.js:653:20)
>     at platform_view$.HtmlElementView.new.[_createHtmlElementView] (http://localhost:51276/packages/flutter/src/widgets/platform_view.dart.lib.js:611:30)
>     at platform_view$._PlatformViewLinkState.new.[_initialize] (http://localhost:51276/packages/flutter/src/widgets/platform_view.dart.lib.js:1248:318)
>     at platform_view$._PlatformViewLinkState.new.initState (http://localhost:51276/packages/flutter/src/widgets/platform_view.dart.lib.js:1229:24)
>     at framework.StatefulElement.new.[_firstBuild] (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:54755:54)
>     at framework.StatefulElement.new.mount (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:31553:26)
>     at framework.StatelessElement.new.inflateWidget (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30308:16)
>     at framework.StatelessElement.new.updateChild (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30162:25)
>     at framework.StatelessElement.new.performRebuild (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:31589:31)
>     at framework.StatelessElement.new.rebuild (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30660:12)
>     at framework.StatelessElement.new.[_firstBuild] (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:31557:12)
>     at framework.StatelessElement.new.mount (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:31553:26)
>     at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30308:16)
>     at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30162:25)
>     at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:47574:29)
>     at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30308:16)
>     at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30162:25)
>     at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:47574:29)
>     at framework.SingleChildRenderObjectElement.new.inflateWidget (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30308:16)
>     at framework.SingleChildRenderObjectElement.new.updateChild (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30162:25)
>     at framework.SingleChildRenderObjectElement.new.mount (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:47574:29)
>     at _LayoutBuilderElement.new.inflateWidget (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30308:16)
>     at _LayoutBuilderElement.new.updateChild (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:30162:25)
>     at http://localhost:51276/packages/flutter/src/widgets/layout_builder.dart.lib.js:136:33
>     at framework.BuildOwner.new.buildScope (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:54201:13)
>     at _LayoutBuilderElement.new.[_layout] (http://localhost:51276/packages/flutter/src/widgets/layout_builder.dart.lib.js:119:36)
>     at http://localhost:51276/packages/flutter/src/rendering/layer.dart.lib.js:3224:11
>     at object$.PipelineOwner.new.[_enableMutationsToDirtySubtrees] (http://localhost:51276/packages/flutter/src/rendering/layer.dart.lib.js:6225:9)
>     at layout_builder._RenderLayoutBuilder.new.rebuildIfNecessary (http://localhost:51276/packages/flutter/src/widgets/layout_builder.dart.lib.js:243:16)
>     at layout_builder._RenderLayoutBuilder.new.performLayout (http://localhost:51276/packages/flutter/src/widgets/layout_builder.dart.lib.js:343:12)
>     at layout_builder._RenderLayoutBuilder.new.layout (http://localhost:51276/packages/flutter/src/rendering/layer.dart.lib.js:3187:14)
>     at view.RenderView.new.performLayout (http://localhost:51276/packages/flutter/src/rendering/layer.dart.lib.js:4672:58)
>     at object$.PipelineOwner.new.flushLayout (http://localhost:51276/packages/flutter/src/rendering/layer.dart.lib.js:6202:107)
>     at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:51276/packages/flutter/src/rendering/layer.dart.lib.js:5485:26)
>     at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:51276/packages/flutter/src/widgets/widget_span.dart.lib.js:56995:15)
>     at binding$5.WidgetsFlutterBinding.new.[_handlePersistentFrameCallback] (http://localhost:51276/packages/flutter/src/rendering/layer.dart.lib.js:5449:12)
>     at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:51276/packages/flutter/src/scheduler/binding.dart.lib.js:762:9)
>     at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:51276/packages/flutter/src/scheduler/binding.dart.lib.js:731:37)
>     at http://localhost:51276/packages/flutter/src/scheduler/binding.dart.lib.js:640:14
>     at internalCallback (http://localhost:51276/dart_sdk.js:25329:11)
> The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9101?uri=http%3A%2F%2F127.0.0.1%3A51313%2FVRDXgP5Yj14%3D
> Application finished.

</details>

<details>
  <summary>Flutter Doctor</summary>

> [√] Flutter (Channel dev, 2.3.0-16.0.pre, on Microsoft Windows [Version 10.0.19043.985], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
> [√] Chrome - develop for the web
> [√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.10.0)
> [√] Android Studio (version 4.2.0)
> [√] IntelliJ IDEA Community Edition (version 2019.3)
> [√] VS Code (version 1.56.2)
> [√] Connected device (4 available)
> 
> • No issues found!

</details>

<details>
  <summary>pubspec.yaml</summary>

```
name: myproject
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_web_view: ^1.5.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

```
</details>

I created a new Flutter project from scratch using `flutter create`. For reproducibility:

<details>
  <summary>main.dart</summary>

```
import 'package:flutter/material.dart';
import 'package:easy_web_view/easy_web_view.dart';

void main() {
  runApp(EasyWebView(
    onLoaded: () {},
    src: 'https://flutter.dev',
    isHtml: false, // Use Html syntax
    isMarkdown: false, // Use markdown syntax
    convertToWidgets: false, // Try to convert to flutter widgets
    // width: 100,
    // height: 100,
  ));
}
```

</details>

I understood that web-browsers depend on the packages `dart:html` and `dart:ui` ([working example](https://stackoverflow.com/questions/58150503/webview-in-flutter-web)) whereas mobile devices are using the flutter `webview` package. This library is making use of that but the problem has to lay somewhere else.

**Comment by berat-cakir** [comment]
I dont know what exactly was causing the issue but I tried out the example and it works:

[Please check here](https://github.com/rodydavis/easy_web_view/tree/master/example/lib)

**Comment by johncharris** [comment]
@berat-cakir Did you figure out what this isn't working? I'm having the same issue.

**Comment by berat-cakir** [comment]
> @berat-cakir Did you figure out what this isn't working? I'm having the same issue.

Make sure you're using the normal Flutter version (Stable) and not Dev or Beta channel
