### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by CaptainDario** [rodydavis/easy_web_view#63]
Thank you for this awesome plugin.

It would be awesome to have desktop support with this plugin.
Are there plans to support Linux, Windows and MacOS?

**Comment by rodydavis** [comment]
I just created a PR for windows! Going to look at windows and macos with similar approaches

**Comment by CaptainDario** [comment]
@rodydavis how about using [this plugin](https://pub.dev/packages/flutter_macos_webview/install) for mac ([some docs](https://morioh.com/p/fb47ce1bdd32))?
