### ISSUE TITLE
CSP issue

### ISSUE THREAD

**Issue by ganadevprajapathy** [rodydavis/easy_web_view#67]
Tried to load up 'https://www.openstreetmap.org/' using the example project. The page did not load up, and got the following error,

Refused to frame 'https://www.openstreetmap.org/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

Is there something that could be done to load?

**Comment by rodydavis** [comment]
Happy to review a PR if needed, closing for now.
