### ISSUE TITLE
Disable CORS

### ISSUE THREAD

**Issue by ganadevprajapathy** [rodydavis/easy_web_view#68]
Can we disable CORS?

**Comment by rodydavis** [comment]
This is up to the website and on th web will require the correct headers.

Could you give an example of what you are trying to do?

**Comment by stoneLee81** [comment]
for instance, access https://www.baidu.com website, will cause CORS problem, can you suggest how to avoid this? @rodydavis

**Comment by rodydavis** [comment]
This cannot be disabled in the browser
