### ISSUE TITLE
Dependencies out of date

### ISSUE THREAD

**Issue by cksoft0807** [rodydavis/easy_web_view#71]
Hi, some dependencies out of date. Example here, url_launcher:

Because permission_handler >=5.0.1+2 <5.1.0 depends on permission_handler_platform_interface 2.0.1 and permission_handler >=5.0.1 <=5.0.1+1 depends on permission_handler_platform_interface ^2.0.1, permission_handler >=5.0.1 <5.1.0 requires permission_handler_platform_interface ^2.0.1.
And because permission_handler ^5.1.0 depends on permission_handler_platform_interface ^2.0.2, permission_handler ^5.0.1 requires permission_handler_platform_interface ^2.0.1.
And because easy_web_view >=1.5.0 depends on permission_handler ^5.0.1+1 and permission_handler_platform_interface ^2.0.1 depends on plugin_platform_interface ^1.0.2, easy_web_view >=1.5.0 requires plugin_platform_interface ^1.0.2.
And because url_launcher >=6.0.6 depends on url_launcher_platform_interface ^2.0.3 which depends on plugin_platform_interface ^2.0.0, easy_web_view >=1.5.0 is incompatible with url_launcher >=6.0.6.
So, because foody_express depends on both url_launcher ^6.0.9 and easy_web_view ^1.5.0, version solving failed.
pub get failed (1; So, because xxx depends on both url_launcher ^6.0.9 and easy_web_view ^1.5.0, version solving failed.)
exit code 1

**Comment by rodydavis** [comment]
Sure I can try to update tomorrow!

**Comment by alexanderkenney** [comment]
Thank you @rodydavis

**Comment by ahetawal-p** [comment]
Hi @rodydavis is this released yet ? Not able to use this package in my current app until the latest version with the fix is released.

**Comment by alexanderkenney** [comment]
@ahetawal-p - there does seem to be an easy_web_view2 in the pub.dev library. This is effectively easy_web_view with the dependencies updated. We will be testing this over the coming days and will switch back to this library once @rodydavis has had the chance to update the dependencies (I'm assuming he has a pretty busy schedule!)

**Comment by rodydavis** [comment]
Should be resolved now
