### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by jeejeestudio** [rodydavis/easy_web_view#76]
Hi, I (as a noob) am trying your plugin but I'm getting this error:  No named parameter with the name 'isHtml'

I simply copied your example to main.dart overwriting anything that there was.
When hovering over EasyWebView there seems no option for isHtml.

Do you have a solution?

Thanks.

**Comment by patana93** [comment]
Same here

**Comment by rodydavis** [comment]
Fixed on **2.0.0**!
