### ISSUE TITLE
Get and Set Cookies support?

### ISSUE THREAD

**Issue by nemoryoliver** [rodydavis/easy_web_view#9]
Does this plugin support or will support these features?

**Comment by rodydavis** [comment]
I don’t think so, but I can look into it. Always welcome to PRs

**Comment by nemoryoliver** [comment]
> I don’t think so, but I can look into it. Always welcome to PRs

I wish you could add those features. especially be able to get cookies even with HttpOnly attribute

**Comment by rodydavis** [comment]
If you want a pure implementation you are welcome to copy the source. This is outside the scope of the plugin. PRs are welcome
